### ISSUE TITLE
New Installation of Pi Control Does Not Work

### ISSUE THREAD

**Issue by rob280z** [jetechteam/picontrol#13]
Using a brand new Raspberry Pi 3B+, I installed Retropie retropie-buster-4.7.1-rpi2_3 with no issues.  I then followed the instructions to install Pi Control and saw the following error during that installation:

Running Adafruit_PureIO-1.1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jjRpSA/Adafruit_PureIO-1.1.7/egg-dist-tmp-rXP60S
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/spi.py", line 386
    ) from e
         ^
SyntaxError: invalid syntax

At the end of the Pi Control installation it reported:

Installation Complete.................
You must reboot for changes to take effect, reboot now? (y/n):

After rebooting I could not bring up the web app using a browser in Windows.  I got the following message:
"This site can’t be reached"
However, I was still able to access the retropie folders using Windows explorer.

It was suggested to try and run picontrol from a terminal and when I did I got the following:

pi@retropie:~ $ cd picontrol
pi@retropie:~/picontrol $ python picontrol.py
Traceback (most recent call last):
  File "/home/pi/scripts/picontrol/webserver/picontrol_web.py", line 6, in <module>
    from flask_api import status
  File "/usr/local/lib/python2.7/dist-packages/flask_api/__init__.py", line 1, in <module>
    from flask_api.app import FlaskAPI
  File "/usr/local/lib/python2.7/dist-packages/flask_api/app.py", line 6, in <module>
    from flask_api.request import APIRequest
  File "/usr/local/lib/python2.7/dist-packages/flask_api/request.py", line 58
    raise e from None
               ^
SyntaxError: invalid syntax

Can anyone identify what the issue may be?  Do I need to install an older version of retropie?

**Comment by rob280z** [comment]
Does Pi Control need to be updated for python 3?

**Comment by Eilermoon** [comment]
I'm not sure if anyone still follows this, but I had this same issue yesterday. Buttons work correctly after installing, but browser PiControl doesn't work and my LED flashes 3 times intermittently. I'm not exactly sure what the 3 flashes means, but I would guess it's something about NFC not working. 

I found an old 4.4 version of RetroPi, thinking it was the updated version of RetroPi that was the issue. This time nothing works, the buttons don't function correctly and the LED is on full-time.

I don't have a solution, just wanted to document my issue here. I'm relatively new to Python but might try to tear into the code soon to see what I understand!
